version: '3.8'

services:
  sensor-adapter:
    build: .
    ports:
      - "8002:${APP_PORT}"       # HTTP API
      - "9999:${APP_TCP_PORT}"       # TCP сервер
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data_sensors:/var/lib/postgresql/data
    ports:
      - "5435:${POSTGRES_PORT}"

volumes:
  postgres_data_sensors:
